// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWebMVC.Data;

#nullable disable

namespace SalesWebMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SalesWebMVC.Data.Entity.DepartmentEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("DhInclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dh_inclusao");

                    b.Property<string>("DsNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ds_nome");

                    b.HasKey("Id");

                    b.ToTable("TB_DEPARTMENT");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.SalesRecordEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("DhInclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dh_inclusao");

                    b.Property<int>("FkSeller")
                        .HasColumnType("int")
                        .HasColumnName("fk_seller");

                    b.Property<int>("SaleStatus")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("ds_valor");

                    b.HasKey("Id");

                    b.HasIndex("FkSeller");

                    b.ToTable("TB_SALESRECORD");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.SellerEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("DhAniversario")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dh_aniversario");

                    b.Property<DateTime>("DhInclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dh_inclusao");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ds_email");

                    b.Property<string>("DsNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ds_nome");

                    b.Property<int>("FkDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("fk_departamento");

                    b.Property<double>("NrSalario")
                        .HasColumnType("double")
                        .HasColumnName("nr_salario");

                    b.HasKey("Id");

                    b.HasIndex("FkDepartamento");

                    b.ToTable("TB_SELLER");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.SalesRecordEntity", b =>
                {
                    b.HasOne("SalesWebMVC.Data.Entity.SellerEntity", "Seller")
                        .WithMany("SalesRecords")
                        .HasForeignKey("FkSeller")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.SellerEntity", b =>
                {
                    b.HasOne("SalesWebMVC.Data.Entity.DepartmentEntity", "Department")
                        .WithMany("ListSeller")
                        .HasForeignKey("FkDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.DepartmentEntity", b =>
                {
                    b.Navigation("ListSeller");
                });

            modelBuilder.Entity("SalesWebMVC.Data.Entity.SellerEntity", b =>
                {
                    b.Navigation("SalesRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
